### ISSUE TITLE
Create a SpringController rather than GlobalKey

### ISSUE THREAD

**Issue by josh-burton** [KaushickSArgekar/spring#1]
Using a GlobalKey to control an animation doesn't feel right. I feel like it's exposing an implementation detail (SpringState) to the user.

What about creating a SpringController instead? Similar to ScrollController, PageViewController etc.

**Comment by KaushickSArgekar** [comment]
Added a Spring controller as you asked.

The issue is fixed in the latest spring 2.0 with a lot more added features.
Check it out. (https://pub.dev/packages/spring)

Thanks for the support.
