### ISSUE TITLE
Animation plays on every state change

### ISSUE THREAD

**Issue by giorgi-abashidze** [KaushickSArgekar/spring#3]
Animation plays on every setState method call, which i dont want. i want to animate only when GestureDetector onTap happens, any solutions?

**Comment by KaushickSArgekar** [comment]
The issue is fixed in the latest spring 2.0 with a lot more added features.
Check it out. (https://pub.dev/packages/spring)

**Comment by GustavoFigueira** [comment]
Same here! And I'm using version `spring: ^2.0.2`

**Comment by KaushickSArgekar** [comment]
> Same here! And I'm using version `spring: ^2.0.2`

Have u tried using different controllers?

**Comment by CalvinTp** [comment]
Same here, I am also using spring: ^2.0.2 and the animation is still played on each setState
